let monkeys = [
  {
    number: 0,
    items: [54, 53],
    operation: 'multiply',
    operationNum: 3,
    test: 2,
    true: 2,
    false: 6,
    inspectedNum: 0,
  },
  {
    number: 1,
    items: [95, 88, 75, 81, 91, 67, 65, 84],
    operation: 'multiply',
    operationNum: 11,
    test: 7,
    true: 3,
    false: 4,
    inspectedNum: 0,
  },
  {
    number: 2,
    items: [76, 81, 50, 93, 96, 81, 83],
    operation: 'add',
    operationNum: 6,
    test: 3,
    true: 5,
    false: 1,
    inspectedNum: 0,
  },
  {
    number: 3,
    items: [83, 85, 85, 63],
    operation: 'add',
    operationNum: 4,
    test: 11,
    true: 7,
    false: 4,
    inspectedNum: 0,
  },
  {
    number: 4,
    items: [85, 52, 64],
    operation: 'add',
    operationNum: 8,
    test: 17,
    true: 0,
    false: 7,
    inspectedNum: 0,
  },
  {
    number: 5,
    items: [57],
    operation: 'add',
    operationNum: 2,
    test: 5,
    true: 1,
    false: 3,
    inspectedNum: 0,
  },
  {
    number: 6,
    items: [60, 95, 76, 66, 91],
    operation: 'multiply',
    operationNum: 'old',
    test: 13,
    true: 2,
    false: 5,
    inspectedNum: 0,
  },
  {
    number: 7,
    items: [65, 84, 76, 72, 79, 65],
    operation: 'add',
    operationNum: 5,
    test: 19,
    true: 6,
    false: 0,
    inspectedNum: 0,
  },
]

module.exports = { monkeys };